
# Paths to data files
data:
  workspace:  #/pfs/work7/workspace/scratch/tu_zxmav84-ds_project/
  data:  /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data 
  orthophotos:  /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/orthophotos 
  building_boxes: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/building_boxes 
  dwd: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/DWD
  sentinel: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/sentinel
  landsat: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/landsat
  potsdam: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/potsdam
  LoveDA: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/LoveDA
  ES_raw:  /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/ECOSTRESS/raw_h5/
  ES_tiffs: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/ECOSTRESS/geoTiff/
  model_weights: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/model_weights
  segmentation_output: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/segmentation_output/
  nutzungsdaten: /pfs/work7/workspace/scratch/tu_zxmav84-ds_project/data/nutzungsdaten/
# Bounding Boxes for locations we analyze
bboxes: 
  munich: [11.310790,47.980475,11.855986,48.385189]
api:
  path: https://m2m.cr.usgs.gov/api/api/json/stable/